export class applicationDetails {
    aadhar:any;
    phoneNumber : any ;
    name:string|undefined;
    dob : any|undefined;
    email : string | undefined;
    religion:string|undefined;
    community:string|undefined;
    fatherName:string|undefined;
    motherName:string|undefined;
    annualIncome:any|undefined;
    institution:string |undefined;
    presentClass:string | undefined;
    presentClassYear:any| undefined;
    modeOfStudy:string | undefined;
    classStartDate: any |undefined;
    university:string |undefined;
    instiCode : string | undefined;
    previousClass:string |undefined;
    previousClassYear:any|undefined;
    previousPercentage:number|undefined;
    tenthRollNo:any|undefined;
    tenthBoard:any|undefined;
    tenthYear:any|undefined;
    tenthPercentage:any|undefined;
    twelthRollNo:any|undefined;
    twelthBoard:any|undefined;
    twelthYear:any|undefined;
    twelthPercentage:any|undefined;
    admissionFee:any|undefined;
    tuitionFee:any|undefined;
    otherFee:any|undefined;
    isDisabled:any|undefined;
    typeofDisability:any|undefined;
    disabilityPercenage:any|undefined;
    maritalStatus:any|undefined;
    parentsProfession:any|undefined;
    state:string|undefined;
    district:string|undefined;
    taluk:string|undefined;
    houseNo:string|undefined;
    streetNo:string|undefined;
    pincode:any|undefined;   
    gender:any|undefined;
    scheme:any|undefined;
    finalStatus: String | undefined;
}
